version: '3.7'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    network_mode: bridge
    expose:
      - 6379

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    network_mode: bridge
    environment:
      - MYSQL_DATABASE=saas
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_CLIENT=mysql
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
    ]
    volumes:
      - ./db_data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d

  api:
    build: .
    container_name: api
    restart: unless-stopped
    network_mode: bridge
    command: /bin/sh -c 'npm install && nodemon -e js,html index.js'
    ports:
      - 5000:5000
    volumes:
      - .:/src
      - /src/node_modules
    links:
      - redis
      - mariadb